export const studentDashboardStyles = {
  container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 text-slate-900 dark:text-slate-100",
  headerBanner: "relative overflow-hidden bg-slate-900 text-white rounded-2xl p-6 sm:p-8 shadow-md border border-slate-800",
  headerAccentGlow: "absolute -right-20 -top-20 w-80 h-80 bg-blue-600/20 rounded-full blur-3xl pointer-events-none",
  headerInner: "relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6",
  quickStatsGrid: "grid grid-cols-2 sm:grid-cols-4 gap-4",
  statBox: "bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-xl p-4 shadow-xs hover:shadow-md transition-all text-slate-900 dark:text-slate-100",
  sectionHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-2 border-b border-slate-200/80 dark:border-slate-800",
  sectionTitle: "text-lg font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2.5",
  requestCard: "bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 rounded-xl p-5 shadow-xs hover:border-blue-300 dark:hover:border-blue-700/60 hover:shadow-md transition-all",
  tableCard: "bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs overflow-hidden",
  tableHeader: "bg-slate-50/90 dark:bg-slate-800/90 border-b border-slate-200 dark:border-slate-800 text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider",
  searchBar: "flex items-center gap-2 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-700 dark:text-slate-200 w-full sm:w-72 focus-within:ring-1 focus-within:ring-blue-500 transition-all",
  modalOverlay: "fixed inset-0 bg-slate-950/70 backdrop-blur-xs z-50 flex items-center justify-center p-4",
  modalContent: "bg-white dark:bg-slate-900 rounded-2xl max-w-lg w-full p-6 shadow-2xl space-y-5 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white",
} as const;
